---
title: "da-ws-08-1"
author: Jannis Gottwald, Lukas Ditzel, Michaela Vorndran, Maite Lezama Valdez, Alexander
  Jorns,
date: "17 Dezember 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(mgcv)

path_main <- ("C:/Users/Michaela Vorndran/Dropbox/Studium/Master/Datenanalyse/Github/msc-phygeo-class-of-2016-MVorndran/data_analysis/")
path_data <- paste0(path_main, "data/")
wood <- read.csv(paste0(path_data, "hessen_holzeinschlag_1997-2014_clean.csv"))


gamt<-lapply(seq(3,13), function(k){
  ret <- lapply(seq(100), function(n){
      set.seed(n)
      s1 <-sample(nrow(wood), 0.8*nrow(wood))
      train <- wood[s1,]
      test <- wood[-s1,]
      mod <- gam(Buche ~ s(Eiche, k=k, fx=TRUE), data=train) #keine penalty regression
      pred <- as.numeric(predict(mod, newdata = test))
      obsv <- test$Buche
      rmse <- sqrt(mean((pred-obsv)**2))
      r_sq <- summary(mod)$r.sq
      return(c(rmse, r_sq))
      })
  
      rmse_test <- as.numeric(lapply(ret, function(l) l[[1]]))
      mean_rmse <- mean(rmse_test)
      sd_rmse <- sd(rmse_test)
      r_sq_test <- as.numeric(lapply(ret, function(l) l[[2]]))
      mean_r_sq <- mean(r_sq_test)
      return(c(mean_rmse, sd_rmse, mean_r_sq))
})
gamtdf <- data.frame(matrix(unlist(gamt), nrow= length(gamt), byrow = T))
gamtdf$knots <- c(3:13)
names(gamtdf) <- c("mean_rmse", "SD_rmse", "adj.R2", "knots")
gamtdf$SD_rmse <- gamtdf$SD_rmse / max(gamtdf$mean_rmse)
gamtdf$mean_rmse <- gamtdf$mean_rmse / max(gamtdf$mean_rmse)

gamtdf$sdplus <- gamtdf$mean_rmse+gamtdf$SD_rmse
gamtdf$sdminus <- gamtdf$mean_rmse-gamtdf$SD_rmse
gamtdf
```
```{r pressure, echo=FALSE}
plot(gamtdf$knots, gamtdf$mean_rmse, type="l", ylim=c(-0.1, 1.5), col = "black", lwd = 2, ylab = "RMSE, SD(RMSE), adj.R²", xlab="knots")
lines(gamtdf$knots, gamtdf$sdplus, col = "red", lty = "dotted")
lines(gamtdf$knots, gamtdf$sdminus, col = "red", lty = "dotted")
lines(gamtdf$knots, gamtdf$adj.R2, col = "blue")

legend("topleft", legend=c("SD(RMSE)", "adj.R2", "RMSE" ), col=c("red", "blue", "black"), lty= c(3,1,1), cex=0.8)
```

